import express, {Router} from 'express';
import isLoggedIn from '../../../src/middleware/middleware.ts';
import asyncErrorHandler from '../../../services/asyncErrorHandler.ts';
import { createCourse, deleteCourse, getAllCourse, getSingleCourse } from '../../../controller/institute/course/course.controller.ts';
import {multer} from '../../../src/middleware/multerMiddleware.ts';
import { storage } from '../../../services/cloudinaryConfig.ts';
const upload = multer({ storage: storage });
const router:Router = express.Router();
router.route('/course').post(asyncErrorHandler(isLoggedIn), upload.single('courseThumbnail'), asyncErrorHandler(createCourse)).get(asyncErrorHandler(getAllCourse));
router.route('/course/:id').get(asyncErrorHandler(getSingleCourse)).delete(asyncErrorHandler(isLoggedIn), asyncErrorHandler(deleteCourse))  ;
export default router;
